### ISSUE TITLE
Limit size of PrivateData blob

### ISSUE THREAD

**Issue by dwightkelly** [open-automation/SwitchJobContentsToPrivateData#3]
There's a limit to how much data Switch PrivateData blob can contain. Not documented; however, it's a String so probably 255 or 1024 bytes. Check file size and truncate or error if larger than this limit.

**Comment by dominickp** [comment]
Dwight, did some testing today and wasn't able to reproduce this. Got to 10,000 characters within a PD key and it seems to handle it fine.

```
function jobArrived( s : Switch, job : Job )
{
    var blob = '';
    var loops = 0;
    var max_loops = 10000;
    var pd_key = "test";

    do {
       blob += "1";    
       job.setPrivateData(pd_key, blob);       
       loops++;

    } while (job.getPrivateData(pd_key) === blob && loops < max_loops);

    s.log(2, "PD value length " + job.getPrivateData(pd_key).length );
    s.log(2, "done, looped " + loops );
}
```

**Comment by dwightkelly** [comment]
OK, I didn't know if there was a limit. Just figured it was a string
